/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"C:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\blestack\blelib\ctrl\cc2640_hci_xcxx_sc.a"
"C:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\blestack\blelib\ctrl\cc2640_ll_xcxx_sc.a"
"C:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\blestack\blelib\hci_tl\cc26xx_hci_tl_none.a"
"C:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\blestack\blelib\host\cc26xx_att_xcxx_sc.a"
"C:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\blestack\blelib\host\cc26xx_gap_xcxx_sc.a"
"C:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\blestack\blelib\host\cc26xx_gatt_xcxx_sc.a"
"C:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\blestack\blelib\host\cc26xx_l2cap_xcxx_sc.a"
"C:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\blestack\blelib\host\cc26xx_profiles_xcxx_sc.a"
"C:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\blestack\blelib\host\cc26xx_smp_xcxx_sc.a"
"C:\ti\simplelink_cc2640r2_sdk_1_35_00_33\source\ti\blestack\blelib\host\cc26xx_sm_xcxx_sc.a"
